
import React from 'react';
import { MindMapNode } from '../types';

interface MindMapProps {
  data: MindMapNode;
  isCollapsed: boolean;
  onToggle: () => void;
}

const MindMap: React.FC<MindMapProps> = ({ data, isCollapsed, onToggle }) => {
  return (
    <div className={`transition-all duration-300 ease-in-out border border-slate-800 rounded-xl bg-slate-900/50 overflow-hidden ${isCollapsed ? 'h-12' : 'min-h-[160px]'}`}>
      <div className="flex items-center justify-between px-4 py-3 bg-slate-800/50 cursor-pointer" onClick={onToggle}>
        <h3 className="font-semibold text-slate-200">Goal Roadmap</h3>
        <span className="text-xs text-slate-400">{isCollapsed ? 'Show' : 'Hide'} Roadmap</span>
      </div>
      {!isCollapsed && (
        <div className="p-6">
          <div className="space-y-4">
            <div className="flex items-center gap-3">
              <div className="w-3 h-3 bg-indigo-500 rounded-full shadow-[0_0_10px_rgba(99,102,241,0.5)]"></div>
              <span className="font-bold text-lg text-white">{data.label}</span>
            </div>
            
            {data.children && data.children.length > 0 && (
              <div className="ml-1.5 border-l-2 border-slate-800 pl-6 space-y-3">
                {data.children.map((child) => (
                  <div key={child.id} className="relative group">
                    <div className="absolute -left-[25px] top-1/2 -translate-y-1/2 w-4 h-[2px] bg-slate-800"></div>
                    <div className="flex items-center gap-2 p-2 rounded-lg bg-slate-800/30 border border-slate-800/50 group-hover:border-indigo-500/30 transition-colors">
                      <div className="w-1.5 h-1.5 bg-indigo-400/50 rounded-full"></div>
                      <span className="text-sm text-slate-300">{child.label}</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
          <p className="mt-6 text-[10px] text-slate-500 uppercase tracking-widest font-semibold opacity-50">Generated by SmartMind AI Protocol</p>
        </div>
      )}
    </div>
  );
};

export default MindMap;
